version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - chatbot-net
    environment:
      - MODEL_URL=http://host.docker.internal:11434/api/chat  # 🧠 Tell backend to use local DeepSeek
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 💡 Key line for container → host access

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - chatbot-net

networks:
  chatbot-net:
